# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ap_8is1xGo9WdLStqEmRNqhVuXg5uIr
"""

1. # Upload hiring.csv
from google.colab import files
uploaded = files.upload()

# Import libraries
import pandas as pd
from sklearn.linear_model import LinearRegression

# Load dataset
df = pd.read_csv('hiring.csv')

print("Original Data:")
print(df)

# ----------------------------
# Data Preprocessing
# ----------------------------

# Convert word numbers to digits
word_to_num = {
    'zero': 0,
    'one': 1,
    'two': 2,
    'three': 3,
    'four': 4,
    'five': 5,
    'six': 6,
    'seven': 7,
    'eight': 8,
    'nine': 9,
    'ten': 10
}

df['experience'] = df['experience'].replace(word_to_num)

# Convert to numeric
df['experience'] = pd.to_numeric(df['experience'], errors='coerce')

# Fill missing values
df['experience'] = df['experience'].fillna(0)
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(df['test_score(out of 10)'].mean())

print("\nCleaned Data:")
print(df)

# ----------------------------
# Model Training
# ----------------------------

X = df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']]
y = df['salary($)']

model = LinearRegression()
model.fit(X, y)

# ----------------------------
# Predictions
# ----------------------------

salary1 = model.predict([[2, 9, 6]])
salary2 = model.predict([[12, 10, 10]])

print("\nPredicted Salary for (2 yr, 9 test, 6 interview):", salary1[0])
print("Predicted Salary for (12 yr, 10 test, 10 interview):", salary2[0])

# Upload file
from google.colab import files
uploaded = files.upload()

# Import libraries
import pandas as pd
from sklearn.linear_model import LinearRegression

# Load dataset (Correct File Name)
df = pd.read_csv('1000_Companies.csv')

print("Original Data:")
print(df.head())

# ----------------------------
# Data Preprocessing
# ----------------------------

# Remove missing values
df = df.dropna()

# One Hot Encoding for State column
df = pd.get_dummies(df, columns=['State'], drop_first=True)

print("\nEncoded Data:")
print(df.head())

# ----------------------------
# Model Training
# ----------------------------

X = df.drop('Profit', axis=1)
y = df['Profit']

model = LinearRegression()
model.fit(X, y)

# ----------------------------
# Prediction
# ----------------------------

# Check column order
print("\nColumns Used for Training:")
print(X.columns)

# Florida prediction
profit = model.predict([[91694.48, 515841.3, 11931.24, 1, 0]])

print("\nPredicted Profit:", profit[0])
