# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ap_8is1xGo9WdLStqEmRNqhVuXg5uIr
"""

# Step 1: Upload file
from google.colab import files
uploaded = files.upload()

# Step 2: Import libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Step 3: Load dataset
df = pd.read_csv('salary.csv')

print("Before Cleaning:")
print(df.info())

# Step 4: Remove missing values
df = df.dropna()

print("\nAfter Cleaning:")
print(df.info())

# Step 5: Define X and y
X = df[['YearsExperience']]
y = df['Salary']

# Step 6: Train model
model = LinearRegression()
model.fit(X, y)

# Step 7: Predict salary for 12 years
salary_12 = model.predict([[12]])

print("\nPredicted Salary for 12 Years Experience:", salary_12[0])

# Step 8: Plot graph
plt.scatter(X, y, color='blue')
plt.plot(X, model.predict(X), color='red')
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.title("Salary Prediction")
plt.show()
