# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ap_8is1xGo9WdLStqEmRNqhVuXg5uIr
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Upload File
from google.colab import files
uploaded = files.upload()   # Upload zoo-data.csv

# Load Dataset
zoo = pd.read_csv("zoo-data.csv")

print("First 5 Rows:")
print(zoo.head())

# Drop animal_name column
zoo = zoo.drop("animal_name", axis=1)

X = zoo.drop("class_type", axis=1)
y = zoo["class_type"]

# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

# Build Model
model = LogisticRegression(max_iter=1000, multi_class='multinomial')
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
print("Multiclass Classification Accuracy:",
      accuracy_score(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix - Multiclass")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()
