# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ap_8is1xGo9WdLStqEmRNqhVuXg5uIr
"""

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# -----------------------------
# Upload Dataset (Colab)
# -----------------------------
from google.colab import files
uploaded = files.upload()   # Upload HR_comma_sep.csv

# -----------------------------
# Load Dataset
# -----------------------------
hr = pd.read_csv("HR_comma_sep.csv")

print("First 5 Rows:")
print(hr.head())

# -----------------------------
# Exploratory Data Analysis
# -----------------------------

# Correlation Heatmap (Fixed)
plt.figure(figsize=(10,6))
sns.heatmap(
    hr.select_dtypes(include=['int64','float64']).corr(),
    annot=True,
    cmap="coolwarm"
)
plt.title("Correlation Matrix")
plt.show()

# Salary vs Retention
pd.crosstab(hr.salary, hr.left).plot(kind='bar')
plt.title("Salary vs Employee Retention")
plt.xlabel("Salary")
plt.ylabel("Number of Employees")
plt.show()

# Department vs Retention
pd.crosstab(hr.Department, hr.left).plot(kind='bar', figsize=(10,6))
plt.title("Department vs Employee Retention")
plt.xlabel("Department")
plt.ylabel("Number of Employees")
plt.show()

# -----------------------------
# Data Preprocessing
# -----------------------------

# Convert categorical columns into numeric
hr = pd.get_dummies(hr, columns=['salary','Department'], drop_first=True)

X = hr.drop("left", axis=1)
y = hr["left"]

# -----------------------------
# Train Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

# -----------------------------
# Build Logistic Regression Model
# -----------------------------
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# -----------------------------
# Prediction
# -----------------------------
y_pred = model.predict(X_test)

# -----------------------------
# Accuracy
# -----------------------------
accuracy = accuracy_score(y_test, y_pred)
print("Binary Classification Accuracy:", accuracy)

# -----------------------------
# Confusion Matrix
# -----------------------------
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix - Binary")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()
