# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hEmPuU8MQ4ruU8T_tqZdYM6W6YSiLUEs
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df = pd.read_csv('canada_per_capita_income.csv')
df.head()

df.columns = ['year', 'income']
df.head()

X = df[['year']]      # Independent variable
y = df['income']     # Dependent variable

model = LinearRegression()
model.fit(X, y)

predicted_income = model.predict([[2020]])
print("Predicted per capita income in 2020: $", predicted_income[0])

print("Intercept (b0):", model.intercept_)
print("Slope (b1):", model.coef_[0])

plt.scatter(df.year, df.income, color='blue')
plt.plot(df.year, model.predict(df[['year']]), color='red')
plt.xlabel("Year")
plt.ylabel("Per Capita Income (US$)")
plt.title("Canada Per Capita Income Prediction")
plt.show()
