# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsrCw7m8w8InS1DoB7KQcmB0QHdJA56S
"""

# Upload dataset in Google Colab

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Replace with your actual file name if different
df = pd.read_csv('iris (1).csv')

# View dataset
print("Dataset Preview:")
print(df.head())

print("\nDataset Info:")
print(df.info())

# Step 1: Import Libraries
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Step 2: Prepare Data
X = df.iloc[:, :-1]   # Features
y = df.iloc[:, -1]    # Target

# Encode target if categorical
le = LabelEncoder()
y = le.fit_transform(y)

# Step 3: Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 4: Train Model
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Step 5: Prediction
y_pred = rf.predict(X_test)

# Step 6: Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
