# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147h_J9lMGJHjt4_xlMPaqPwuBBWPlAG8
"""

from google.colab import files
import pandas as pd

files.upload()  # select housing.csv

import pandas as pd

df = pd.read_csv('housing.csv')

df.info()

df.head()

df.describe()

df['ocean_proximity'].value_counts()

df.isnull().sum()[df.isnull().sum() > 0]
